In [1]:
print("Python is fun!")

Python is fun!

In [2]:
patient_id = 1 # int (whole number)
temperature = 36.7 # float (decimal)
status = "stable" # string (text)
is_high_risk = False # boolean
print(patient_id, temperature, status)

1 36.7 stable

In [3]:
%pip install pandas

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in .\.venv\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd
df = pd.read_csv("wound_data.csv")
df.head()

   patient_id  temperature    pH  status  healing_days
0           1         36.4  7.08  stable            10
1           2         36.6  7.01  stable            11
2           3         36.7  7.24  stable            13
3           4         36.9  7.33  stable            15
4           5         37.0  7.05  stable            14

In [5]:
df.shape # rows and columns
df.columns # column names
df.info() # dtypes + missing values
df.describe() # simple statistics

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    10 non-null     int64
 1   temperature   10 non-null     float64
 2   pH            10 non-null     float64
 3   status        10 non-null     str
 4   healing_days  10 non-null     int64
dtypes: float64(2), int64(2), str(1)
memory usage: 532.0 bytes

       patient_id  temperature         pH  healing_days
count    10.00000    10.000000  10.000000     10.000000
mean      5.50000    37.040000   7.265000     17.400000
std       3.02765     0.397772   0.185308      6.095536
min       1.00000    36.400000   7.010000     10.000000
25%       3.25000    36.750000   7.105000     13.250000
50%       5.50000    37.050000   7.275000     16.000000
75%       7.75000    37.350000   7.397500     21.250000
max      10.00000    37.600000   7.530000     29.000000

In [6]:
import numpy as np #numpy is a library for numerical computing
readings = np.array([36.5, 37.2, 38.1]) #accepts an array of numbers

print("Tempreture Mean:", readings.mean())
print(readings > 37.7)

temp = df["temperature"].to_numpy() #tonumpy() converts a pandas series to a numpy array
ph = df["pH"].to_numpy()

correlation = np.corrcoef(temp, ph)[0, 1] #np.corrcoef() calculates the correlation coefficient between two arrays
print("Correlation:", round(correlation, 2))

Tempreture Mean: 37.26666666666667
[False False  True]
Correlation: 0.83

In [7]:
df["high_temperature"] = df["temperature"] > 37.7 #df[] is used to create a new column in the dataframe
df["high_pH"] = df["pH"] > 7.65
df["combined_risk"] = ( #df[] can even combine multiple columns to create a new column, very nice
 0.65 * (df["temperature"] - 36.5)
 + 0.35 * (df["pH"] - 7.0) * 2
)
# these are examples of data manipulation, which is important for machine learning as AI handles data better this way.

In [8]:
# Classification: a two-condition prediction rule
df["prediction"] = np.where( #df[] made a new column, np.where() is a conditional function that returns one value if the condition is true/false
 (df["temperature"] > 37.7) & (df["pH"] > 7.65),
 "deteriorating", "stable"
)

df["correct"] = df["prediction"] == df["status"]
accuracy = df["correct"].mean()
print("Accuracy:", round(accuracy, 2)) 
# Save the updated table as a new CSV file
df.to_csv("wound_data_with_predictions.csv",
index=False)

mistakes = df[df["correct"] == False]
mistakes[["patient_id", "temperature",
 "pH", "status", "prediction"]]

Accuracy: 0.9

   patient_id  temperature   pH         status prediction
8           9         37.5  7.5  deteriorating     stable

In [9]:
# Open the CSV that was already saved
df = pd.read_csv("wound_data_with_predictions.csv")

# Create a new column
new_column = pd.DataFrame({
 "risk_level": np.where( (df["temperature"] > 37.7) & (df["pH"] > 7.65),
 "high", "low"
 )
})

# Append the new column to the DataFrame
df = pd.concat([df, new_column], axis=1) #axis means stack the new column horizontally (axis=1) instead of vertically (axis=0)

# Drop a column
df = df.drop(columns=["correct"]) #df.drop() removes a column from the DataFrame

# Remove one value by replacing it with a missing value
df.loc[df["patient_id"] == 9, "pH"] = np.nan #this line replaces the pH value for patient_id 9 with NaN (missing value)

# Save the final updated version
df.to_csv("wound_data_updated.csv", index=False)
print(df)

   patient_id  temperature    pH         status  healing_days  \
0           1         36.4  7.08         stable            10
1           2         36.6  7.01         stable            11
2           3         36.7  7.24         stable            13
3           4         36.9  7.33         stable            15
4           5         37.0  7.05         stable            14
5           6         37.1  7.18         stable            17
6           7         37.2  7.31         stable            19
7           8         37.4  7.42         stable            22
8           9         37.5   NaN  deteriorating            29
9          10         37.6  7.53         stable            24

   high_temperature  high_pH  combined_risk prediction risk_level
0             False    False         -0.009     stable        low
1             False    False          0.072     stable        low
2             False    False          0.298     stable        low
3             False    False          0.491     stable        low
4             False    False          0.360     stable        low
5             False    False          0.516     stable        low
6             False    False          0.672     stable        low
7             False    False          0.879     stable        low
8             False    False          1.000     stable        low
9             False    False          1.086     stable        low

In [10]:
df.shape # rows and columns
df.columns # column names
df.info() # dtypes + missing values
df.describe() # simple statistics

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   patient_id        10 non-null     int64
 1   temperature       10 non-null     float64
 2   pH                9 non-null      float64
 3   status            10 non-null     str
 4   healing_days      10 non-null     int64
 5   high_temperature  10 non-null     bool
 6   high_pH           10 non-null     bool
 7   combined_risk     10 non-null     float64
 8   prediction        10 non-null     str
 9   risk_level        10 non-null     str
dtypes: bool(2), float64(3), int64(2), str(3)
memory usage: 792.0 bytes

       patient_id  temperature        pH  healing_days  combined_risk
count    10.00000    10.000000  9.000000     10.000000      10.000000
mean      5.50000    37.040000  7.238889     17.400000       0.536500
std       3.02765     0.397772  0.175958      6.095536       0.373617
min       1.00000    36.400000  7.010000     10.000000      -0.009000
25%       3.25000    36.750000  7.080000     13.250000       0.313500
50%       5.50000    37.050000  7.240000     16.000000       0.503500
75%       7.75000    37.350000  7.330000     21.250000       0.827250
max      10.00000    37.600000  7.530000     29.000000       1.086000

In [12]:
import pandas as pd
from sklearn.linear_model import LinearRegression
df = pd.read_csv("wound_data_with_predictions.csv")
X = df[["temperature", "pH"]]
y = df["healing_days"]
model = LinearRegression()
model.fit(X, y)
model.predict([[38.2, 7.8]])

c:\Users\chris\OneDrive - AUT University\Documents\dataeng_ai_foundation\.venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([34.98480319])

In [13]:
from sklearn.cluster import KMeans
X = df[["temperature", "pH"]]
kmeans = KMeans(n_clusters=3, random_state=7) #cluster = 3 means to group the data into 3 clusters. 
df["cluster"] = kmeans.fit_predict(X)
print(df[["patient_id", "temperature", "pH",
"cluster"]])

   patient_id  temperature    pH  cluster
0           1         36.4  7.08        0
1           2         36.6  7.01        0
2           3         36.7  7.24        0
3           4         36.9  7.33        2
4           5         37.0  7.05        2
5           6         37.1  7.18        2
6           7         37.2  7.31        2
7           8         37.4  7.42        1
8           9         37.5  7.50        1
9          10         37.6  7.53        1

In [14]:
row = df.iloc[8] #df.iloc is used to select a specific row from df by its index position (8 in this case)
prompt = f"""
Write a short non-diagnostic summary:
Patient ID: {row['patient_id']}
Temperature: {row['temperature']}
pH: {row['pH']}
Prediction: {row['prediction']}
Keep it factual and mention uncertainty.
"""
print(prompt)

Write a short non-diagnostic summary:
Patient ID: 9
Temperature: 37.5
pH: 7.5
Prediction: stable
Keep it factual and mention uncertainty.

In [18]:
df = pd.read_csv("wound_data_with_predictions.csv")
df_rulefail = df.copy()

# Deliberately create one prediction that does not follow the rule
df_rulefail.loc[
 df_rulefail["patient_id"] == 10,
 "prediction"
] = "deteriorating"

# Calculate what the prediction should be according to the rule
df_rulefail["rule_prediction"] = np.where(
 (df_rulefail["temperature"] > 37.7)
 & (df_rulefail["pH"] > 7.65),
 "deteriorating",
 "stable"
)

# Compare the stored prediction with the rule-based prediction
df_rulefail["follows_rule"] = (
 df_rulefail["prediction"]
 == df_rulefail["rule_prediction"]
)

# Display only rule failures
df_rulefail[df_rulefail["follows_rule"] == False]
#this chunk of code is used if a rule exists which the algorithm follows.

,patient_id,temperature,pH,status,healing_days,high_temperature,high_pH,combined_risk,prediction,correct,rule_prediction,follows_rule
9,10,37.6,7.53,stable,24,False,False,1.086,deteriorating,True,stable,False